/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DatenHolenRouteImport } from './routes/datenHolen'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events/$eventId'
import { Route as AuthenticatedEventsEventIdIndexRouteImport } from './routes/_authenticated/events/$eventId/index'
import { Route as AuthenticatedEventsEventIdEditRouteImport } from './routes/_authenticated/events/$eventId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenHolenRoute = DatenHolenRouteImport.update({
  id: '/datenHolen',
  path: '/datenHolen',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsEventIdIndexRoute =
  AuthenticatedEventsEventIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEventsEventIdRoute,
  } as any)
const AuthenticatedEventsEventIdEditRoute =
  AuthenticatedEventsEventIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedEventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/datenHolen': typeof DatenHolenRoute
  '/login': typeof LoginRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRouteWithChildren
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/events/$eventId/edit': typeof AuthenticatedEventsEventIdEditRoute
  '/events/$eventId/': typeof AuthenticatedEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/datenHolen': typeof DatenHolenRoute
  '/login': typeof LoginRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/events/$eventId/edit': typeof AuthenticatedEventsEventIdEditRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/datenHolen': typeof DatenHolenRoute
  '/login': typeof LoginRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRouteWithChildren
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/events/$eventId/edit': typeof AuthenticatedEventsEventIdEditRoute
  '/_authenticated/events/$eventId/': typeof AuthenticatedEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/datenHolen'
    | '/login'
    | '/events/$eventId'
    | '/events/'
    | '/events/$eventId/edit'
    | '/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/datenHolen'
    | '/login'
    | '/events'
    | '/events/$eventId/edit'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/datenHolen'
    | '/login'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/events/'
    | '/_authenticated/events/$eventId/edit'
    | '/_authenticated/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  DatenHolenRoute: typeof DatenHolenRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenHolen': {
      id: '/datenHolen'
      path: '/datenHolen'
      fullPath: '/datenHolen'
      preLoaderRoute: typeof DatenHolenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/$eventId/': {
      id: '/_authenticated/events/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AuthenticatedEventsEventIdIndexRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRoute
    }
    '/_authenticated/events/$eventId/edit': {
      id: '/_authenticated/events/$eventId/edit'
      path: '/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof AuthenticatedEventsEventIdEditRouteImport
      parentRoute: typeof AuthenticatedEventsEventIdRoute
    }
  }
}

interface AuthenticatedEventsEventIdRouteChildren {
  AuthenticatedEventsEventIdEditRoute: typeof AuthenticatedEventsEventIdEditRoute
  AuthenticatedEventsEventIdIndexRoute: typeof AuthenticatedEventsEventIdIndexRoute
}

const AuthenticatedEventsEventIdRouteChildren: AuthenticatedEventsEventIdRouteChildren =
  {
    AuthenticatedEventsEventIdEditRoute: AuthenticatedEventsEventIdEditRoute,
    AuthenticatedEventsEventIdIndexRoute: AuthenticatedEventsEventIdIndexRoute,
  }

const AuthenticatedEventsEventIdRouteWithChildren =
  AuthenticatedEventsEventIdRoute._addFileChildren(
    AuthenticatedEventsEventIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRouteWithChildren
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRouteWithChildren,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  DatenHolenRoute: DatenHolenRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
